version: "3.9"

services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - redis
    restart: always
    volumes:
      # persist the sqlite database on the host
      - ./db.sqlite3:/app/db.sqlite3
      # persist uploaded media/static files and collected staticfiles
      - ./public/static:/app/public/static
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static

  worker:
    build: .
    container_name: celery_worker
    command: celery -A SecurityGuard worker --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
      - web  # ensure web container up first
    restart: always
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./public/static:/app/public/static
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

