version: "3.9"

services:
  web:
    build: .
    container_name: web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - redis
    restart: always
    volumes:
      # persist database in data directory
      - ./data:/app/data
      # persist uploaded media/static files and collected staticfiles
      - ./public/static:/app/public/static
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static
    working_dir: /app

  worker:
    build: .
    container_name: celery_worker
    command: celery -A SecurityGuard worker --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
      - web  # ensure web container up first
    restart: always
    volumes:
      # persist database in data directory
      - ./data:/app/data
      - ./public/static:/app/public/static
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

